### ISSUE TITLE
Suggestion to version 2.0.x

### ISSUE THREAD

**Issue by jpereira** [FreeRADIUS/mod_auth_radius#31]
Hi,

   I would like to propose the way to mod_auth_radius. below some changes to version v2.0.x

1) Add support to libfreeradius-client (the current code is so confuse) to be possible to load the dictionaries.
2) Add support to append any avp/vsa during authorization.

e.g:
```
AuthRadiusSetAttr "Calling-Station-Id" "MyCalling-Station123"
AuthRadiusSetAttr "Alc-Subscriber-Filter" "Ingr-v4:20,Egr-v4:666"
......
AuthRadiusSetAttr "NAS-Port-Id" "http2radius 001"
```

3) Capabilitie to overwrite/append attributes over HTTP Headers

e.g: Configured in apache...
```
AuthRadiusAttrAcceptOverHTTPHeader
 "NAS-Port-Type"
AuthRadiusAttrAcceptOverHTTPHeader "Calling-Station-Id"
```

The client could be send something like:

```
curl -X "NAS-Port-Type: 'Caipirinha para todos'" -X "Alc-Subscriber-Filter: 'Ingr-v4:20,Egr-v4:123" http://myusername:mypassword@portal.xxxxxxxxxxxx.com
```

Conclusion: I have started the implementation. But, I would like to know your suggestions.

**Comment by alandekok** [comment]
On Nov 27, 2015, at 2:08 PM, Jorge Pereira <notifications@github.com> wrote:
> 1) Add support to libfreeradius-client (the current code is so confuse) to be possible to load the dictionaries.

  Please don't use libfreeradius-client.  The code is terrible.  The libfreeradius-radius code is much better.

> 2) Add support to append any avp/vsa during authorization.

  Sure, that's fine.

> e.g:
> 
> AuthRadiusSetAttr "Calling-Station-Id" "MyCalling-Station123"
> AuthRadiusSetAttr "Alc-Subscriber-Filter" "Ingr-v4:20,Egr-v4:666"
> ......
> AuthRadiusSetAttr "NAS-Port-Id" "http2radius 001"
> 
> 3) Capabilitie to overwrite/append attributes over HTTP Headers

  Sure.

**Comment by jpereira** [comment]
4) Return the Reply-Message in http header.

**Comment by alandekok** [comment]
> On Nov 27, 2015, at 2:30 PM, Jorge Pereira <notifications@github.com> wrote:
> 
> 4) Return the Reply-Message in http header.

  Sure...

**Comment by jpereira** [comment]
Great! If possible, make a fork from the master to v2.0.x. could be better?

**Comment by jpereira** [comment]
@alandekok or @arr2036, could open a new branch to v2.0.x?

**Comment by arr2036** [comment]
done
