### ISSUE TITLE
ID and passwords in plain text when Apache LogLevel set to Debug

### ISSUE THREAD

**Issue by MKWorkman** [FreeRADIUS/mod_auth_radius#44]
During some troubleshooting I noticed the event.   I set the .conf file to include LogLevel debug and mod_auth_radius recorded user credentials in plaintext.   

apache2 2.4.7
libapache2-mod-auth-radius 1.5.8-1.2 

Change the site's .conf file to include LogLevel debug. 
Restart apache2 and have someone logon to the site using radius. 

the creds are written to the log files in plain text.  

This is usually a bad thing.   The password should be obscured in the logs.

**Comment by jpereira** [comment]
Can you append those log reports?

**Comment by alandekok** [comment]
> I set the .conf file to include LogLevel debug and mod_auth_radius recorded user credentials in plaintext.

That's pretty much what debug output means.  How else are you going to debug it when something goes wrong?

The normal logging doesn't write passwords to the log file.

**Comment by MKWorkman** [comment]
User passwords should usually never be written to the logs.   Debug or not.

**Comment by alandekok** [comment]
I appreciate your opinion.  But you're wrong.

The *standard* use-case for debugging authentication systems is to show what's going on.  Including passwords.

If you disagree with this, create your own fork of the module.
